### ISSUE TITLE
Index attempted to be read from is out of bounds: 4e

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/sfntly#43]
```
Using font from http://img.dafont.com/dl/?f=escapeviawindow and passing it 
through the java sfnttool tool, it fails when trying to make an eot file

reedy@ubuntu64-web-esxi:/var/www/wiki/mediawiki/extensions/UniversalLanguageSele
ctor/data/fontrepo/fonts/EscapeViaWindow$ java -jar 
/home/reedy/sfntly-builds/java-openjdk-7/sfnttool/sfnttool.jar -e -h -x 
EscapeViaWindow.ttf EscapeViaWindow.eot
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index attempted 
to be read from is out of bounds: 4e
        at com.google.typography.font.sfntly.data.ReadableFontData.readUByte(Unknown Source)
        at com.google.typography.font.sfntly.data.ReadableFontData.readULong(Unknown Source)
        at com.google.typography.font.sfntly.table.core.OS2Table.ulCodePageRange1(Unknown Source)
        at com.google.typography.font.tools.conversion.eot.EOTWriter.writeCodePages(Unknown Source)
        at com.google.typography.font.tools.conversion.eot.EOTWriter.convert(Unknown Source)
        at com.google.typography.font.tools.sfnttool.SfntTool.subsetFontFile(Unknown Source)
        at com.google.typography.font.tools.sfnttool.SfntTool.main(Unknown Source)
```

Original issue reported on code.google.com by `tehre...@gmail.com` on 15 Dec 2013 at 7:07

**Comment by behdad** [comment]
Closed via https://github.com/googlei18n/sfntly/pull/48
